Projeto - Inteligência Artificial na Prática

PUCPR

Aluno: Johnson Santana de Carvalho - johnson@stj.jus.br

# Descrição

Essa atividade tem como objetivo aplicar os conceitos discutidos durante as aulas de Inteligência Artificial na Prática.
Trata-se de um classificador de documentos júridicos utilizando NPL.

Classes Alvos:
* petição  - 37;
* despacho - 409;
* decisão  - 404;
* acórdão  - 536;
* sentença - 550;
* voto     - 781;
* Outros Documentos - 106;




# Obtendo dados

In [2]:
# Download do arquivo que contém dos target e o texto.
#nome do arquivo: documentos.json 1-0PN4PuV0tH8wdag01sNDJnkBPlQT1O4
!gdown 1-0PN4PuV0tH8wdag01sNDJnkBPlQT1O4 # 2.000 registros por classe (7) total 14.000

Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1-0PN4PuV0tH8wdag01sNDJnkBPlQT1O4

but Gdown can't. Please check connections and permissions.


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import XLNetTokenizer, XLNetForSequenceClassification
from torch.utils.data import DataLoader, TensorDataset
import torch
from torch import nn, optim
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report



In [4]:

dados_classes = {
    'target': [37, 409, 404, 536, 550, 781, 106],
    'descricao': ['petição',  'despacho' , 'decisão', 'acórdão', 'sentença', 'voto', 'Outros Documentos']
}
classes_dominio = pd.DataFrame(dados_classes)

In [8]:
# Abertura do arquivo
caminho_arquivo = "/content/documentos_amostra.json"
df = pd.read_json(caminho_arquivo)

In [9]:

# Assuming df is your original DataFrame containing 'target' and 'texto' columns
colunas = ['target', 'texto']
dados = df[colunas]



In [ ]:
# Tokenize input text using XLNet tokenizer
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')
encoded_data = tokenizer(list(dados['texto']), padding=True, truncation=True, return_tensors='pt')

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(encoded_data['input_ids'], dados['target'], test_size=0.2, random_state=42)

# Create PyTorch datasets
train_dataset = TensorDataset(X_train, torch.tensor(y_train.values))
test_dataset = TensorDataset(X_test, torch.tensor(y_test.values))

# Create DataLoader
train_dataloader = DataLoader(train_dataset, batch_size=8, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=8, shuffle=False)

# Load pre-trained XLNet model for sequence classification
model = XLNetForSequenceClassification.from_pretrained('xlnet-base-cased', num_labels=len(classes_dominio))

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=2e-5)

# Training loop
num_epochs = 3
for epoch in range(num_epochs):
    for batch in train_dataloader:
        inputs, labels = batch
        outputs = model(inputs, labels=labels)
        loss = outputs.loss
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

# Evaluation on the test set
model.eval()
all_preds = []
with torch.no_grad():
    for batch in test_dataloader:
        inputs, labels = batch
        outputs = model(inputs)
        logits = outputs.logits
        preds = torch.argmax(logits, dim=1)
        all_preds.extend(preds.cpu().numpy())

# Display classification report
from sklearn.metrics import classification_report


# Calculate metrics
accuracy = accuracy_score(all_labels, all_preds)
f1 = f1_score(all_labels, all_preds, average='weighted')
precision = precision_score(all_labels, all_preds, average='weighted')
recall = recall_score(all_labels, all_preds, average='weighted')

# Display classification report
print(classification_report(all_labels, all_preds, target_names=classes_dominio['descricao']))

# Display additional metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")



/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/760 [00:00<?, ?B/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [ ]:
colunas = ['target', 'texto']
dados = df[colunas]
documentos = dados.values

In [ ]:
#Importar bibliotecas necessárias
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Baixar os recursos necessários do NLTK
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

stopwords.words é uma função ou método comumente utilizado em processamento de linguagem natural (NLP) para remover palavras de parada (stop words) de um texto ou documento. Stop words são palavras que são consideradas irrelevantes para a análise de texto porque aparecem com frequência em muitos documentos e não contribuem significativamente para o significado do texto. Essas palavras incluem artigos, preposições, conjunções e outras palavras comuns, como "a", "o", "de", "para", "e", "ou", entre outras.

Ao remover stop words de um texto, podemos melhorar a qualidade da análise de texto e reduzir o ruído nos dados. Isso é útil em tarefas como classificação de texto, análise de sentimentos, geração de resumos automáticos e muitas outras aplicações de processamento de linguagem natural.

A biblioteca nltk (Natural Language Toolkit) em Python oferece uma lista predefinida de stop words para vários idiomas, incluindo o português, inglês, espanhol, francês, entre outros. A função stopwords.words do nltk permite acessar essas listas de stop words.

Após obter a lista de stop words, aplica-se para filtrar o texto, removendo essas palavras antes de realizar análises mais avançadas. Isso ajuda a reduzir o tamanho do vocabulário e a melhorar a eficácia de técnicas de aprendizado de máquina em tarefas de processamento de texto.

In [ ]:
# Selecionar o documento (idDocumento) e a classe (codTIpoDocumento do CNJ) Base de dados do MNI - Sistema Justiça) DB2
# Recuperar o nome do arquivo json no S3 da amazon pelo idDOcumento  (EXTRATOR) Postgres
# Chamada get para recuperar o Texto do S3 para obter o Json passando o nome do arquivo como parâmetro

# Exemplo de documentos jurídicos classificado

# Pré-processamento dos documentos
stop_words = set(stopwords.words('portuguese'))
stemmer = PorterStemmer()
conteudo = []
classes = []

for classe, documento in documentos:
    palavras = [stemmer.stem(word.lower()) for word in word_tokenize(documento,language='portuguese') if word.lower() not in stop_words]
    conteudo.append(' '.join(palavras))
    classes.append(classe)

In [ ]:
# Vetorização dos documentos
vectorizer = CountVectorizer()
X_treinamento = vectorizer.fit_transform(conteudo)

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.utils.data import TensorDataset, DataLoader

# Assuming the correct public model identifier (replace with actual name):
model_name = "bert-base-portuguese"

# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)


# Criação de embeddings BERT
embeddings = []
for documento in conteudo:
  inputs = tokenizer(documento, return_tensors="pt")
  with torch.no_grad():
    outputs = model(**inputs)
  embeddings.append(outputs.logits.squeeze(0))

OSError: bert-base-portuguese is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [ ]:
# Divisão dos dados em conjunto de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X_treinamento, classes, test_size=0.2, random_state=42)

In [ ]:
# Treinamento do classificador Naive Bayes
classificador = MultinomialNB()
classificador.fit(X_train, y_train)

MultinomialNB()

Neste exemplo:

y_test é a lista das verdadeiras classes dos documentos no conjunto de teste.
y_pred é a lista das previsões do seu modelo para os mesmos documentos.
Cada métrica fornece uma visão diferente do desempenho do seu modelo. A acurácia mede a proporção de previsões corretas, a precisão mede a proporção de previsões positivas que são corretas, a revocação mede a proporção de casos positivos que foram corretamente identificados, e assim por diante.
A matriz de confusão mostra a contagem de verdadeiros positivos, verdadeiros negativos, falsos positivos e falsos negativos, o que permite uma análise mais detalhada dos erros de classificação do modelo.
Estas são apenas algumas das métricas que usamos para avaliar o desempenho do classificador de documentos.

In [ ]:
# Avaliação do modelo
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = classificador.predict(X_test)

# Acurácia
acuracia = accuracy_score(y_test, y_pred)
print("Acurácia:", acuracia)

print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))

# Matriz de Confusão
matriz_confusao = confusion_matrix(y_test, y_pred)
print("Matriz de Confusão:")
print(matriz_confusao)

Acurácia: 0.5757142857142857

Relatório de Classificação:
              precision    recall  f1-score   support

          37       0.77      0.73      0.75       407
         106       0.77      0.28      0.41       398
         404       0.75      0.56      0.64       402
         409       0.67      0.62      0.64       396
         536       0.98      0.22      0.37       418
         550       0.45      0.88      0.59       378
         781       0.40      0.75      0.52       401

    accuracy                           0.58      2800
   macro avg       0.68      0.58      0.56      2800
weighted avg       0.69      0.58      0.56      2800

Matriz de Confusão:
[[298   9   1  12   0  60  27]
 [ 69 112   6  86   2  74  49]
 [  5   3 226  14   0 116  38]
 [  9  13  53 246   0  66   9]
 [  4   4   9   2  94   8 297]
 [  1   1   7   4   0 334  31]
 [  0   3   1   3   0  92 302]]


In [ ]:
import json
import re

pasta_raiz = ""

# Teste com novo documento
def classificar_documento(documento):
    words = [stemmer.stem(word.lower()) for word in word_tokenize(documento) if word.lower() not in stop_words]
    vetorizado = vectorizer.transform([' '.join(words)])
    return classificador.predict(vetorizado)[0]

def extrair_texto(nome_arquivo):
  # Identificando a pasta do arquivo (resto do número presente no nome do arquivo com a quantidade de pastas no google driver)
  texto = ""
  try:
    dados_json = get_json(nome_arquivo)
    if 'error' in dados_json:
      print(f'{dados_json["error"]}')
      return texto

    for pagina in dados_json["paginas"]:
      for elemento in pagina["elementos"]:
        texto = texto + '\n' + elemento["texto"]
  except Exception as e:
    print(f"{nome_arquivo}: Não foi possível ler o jason:", e)
    return texto
  print(f"{nome_arquivo}: Texto extraído")
  return texto

def get_json(nome_arquivo):
  if not validar_nome_arquivo(nome_arquivo):
    return {"error": "O nome do arquivo não está no formato correto:  'registro + . + seq_peca + .json' (^\d{12}.\d+\.json$). Exemplo correto: 202400567624.11.json"}

  with open('/content/' + nome_arquivo, 'r') as arquivo:
    # Carregar os dados JSON
    dados_json = json.load(arquivo)
  return dados_json

def validar_nome_arquivo(nome_arquivo):
    # Expressão regular para validar o formato do CEP
    padrao_nome_arquivo = r'^\d{12}.\d+\.json$'

    # Verifica se o CEP corresponde ao padrão
    if re.match(padrao_nome_arquivo, nome_arquivo):
        return True
    else:
        return False

# Exemplo de utilização em novos documentos


1.  Faça upload o arquivo .json para o colab
2.  Preencha a variável nome_arquivo
3.  Execute o comando abaixo



In [ ]:
# Exemplo de uso
nome_arquivo = "202400493385.74_dec.json"
descricao =" "
novo_documento = extrair_texto(nome_arquivo)
classificacao = classificar_documento(novo_documento)
descricao = classes_dominio.loc[classes_dominio['target'] == classificacao, 'descricao'].values[0]

print(f"O documento {nome_arquivo} foi classificado como '{classificacao} - {descricao}':\n{novo_documento}")

O nome do arquivo não está no formato correto:  'registro + . + seq_peca + .json' (^\d{12}.\d+\.json$). Exemplo correto: 202400567624.11.json
O documento 202400493385.74_dec.json foi classificado como '550 - sentença':



In [ ]:
# Exemplo de uso
nome_arquivo = "202103675498.65.json"
descricao =" "
novo_documento = extrair_texto(nome_arquivo)
classificacao = classificar_documento(novo_documento)
descricao = classes_dominio.loc[classes_dominio['target'] == classificacao, 'descricao'].values[0]

print(f"O documento {nome_arquivo} foi classificado como '{classificacao} - {descricao}':\n{novo_documento}")
print(f"\n\n{nome_arquivo} classificado como: {classificacao} - {descricao}")